# Generated by Django 4.1.7 on 2023-06-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='images')),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
    ]
