# Generated by Django 4.1.7 on 2023-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_news', '0004_remove_news_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='user_id',
            field=models.CharField(default='User.id', max_length=200),
        ),
    ]
